BeanSceneProject/Areas/Administration/Controllers/SettingController.cs
using BeanSceneProject.Data;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace BeanSceneProject.Areas.Administration.Controllers
{
    [Route("Settings")]
    public class SettingController : AdministrationController
    {
        public SettingController(ApplicationDbContext context, UserManager<IdentityUser> userManager, RoleManager<IdentityRole> roleManager) : base(context, userManager, roleManager)
        {

        }
        public IActionResult Index()
        {
            return View();
        }
        [HttpGet, Route("View")]
        public IActionResult ViewSettings()
        {
            var code = _context.RoleCodes.ToList();

            return View(code);
        }
        [HttpGet, Route("{id}/Edit")]
        public IActionResult EditSettings(int id)
        { 
            var code = _context.RoleCodes.Find(id);

            if (code != null)
            {
                var editCode = new RoleCode()
                {
                    Id = code.Id,
                    ManagerCode = code.ManagerCode,
                    StaffCode = code.StaffCode,
                };
                return View(editCode);
            }
            else
            {
                TempData["errorMessage"] = "Model Data is not valid";
                return RedirectToAction("ViewSettings");
            }

        }
        [HttpPost, Route("{id}/Edit")]
        public async Task<IActionResult> EditSettings(RoleCode roleCode)
        {


            var editCode = _context.RoleCodes
                .Where(r => r.Id == roleCode.Id)
                .FirstOrDefault();

            editCode.Id = roleCode.Id;
            editCode.ManagerCode = roleCode.ManagerCode;
            editCode.StaffCode = roleCode.StaffCode;



            _context.RoleCodes.Update(editCode);
            await _context.SaveChangesAsync();
            return RedirectToAction("ViewSettings");
        }
    }
}

BeanSceneProject/Areas/Administration/Views/Setting/EditSettings.cshtml
@model RoleCode

@{
    ViewData["Title"] = "EditSettings";
}

<h1>Edit Codes</h1>

<form asp-controller="Setting" asp-action="EditSettings" method="post" autocomplete="off" class="p-5">

    <div class="mb-3">
        <label class="form-label"> Id</label>
        <input type="text" class="form-control" asp-for="Id" readonly />
    </div>

    <div class="mb-3">
        <label class="form-label">Manager Code</label>
        <input type="text" class="form-control" asp-for=ManagerCode />
        <span asp-validation-for="ManagerCode" class="text-danger"></span>
    </div>

    <div class="mb-3">
        <label class="form-label">Staff Code</label>
        <input type="text" class="form-control" asp-for=StaffCode />
        <span asp-validation-for="StaffCode" class="text-danger"></span>
    </div>

    <div class="d-grid">
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>

</form>

BeanSceneProject/Areas/Administration/Views/Setting/ViewSettings.cshtml
@model IEnumerable<RoleCode>

@{
    ViewData["Title"] = "ViewSettings";
}

<h1>Settings</h1>

<hr />

<form class="p-5">
    <table class="table-responsive table-hover table-bordered" style="width:100%">
        <thead>
            <tr class="active" style="color:white; background-color: steelblue">

                <th class="text-center">Manager Code</th>
                <th class="text-center">Staff Code</th>
                <th class="text-center" style="width:15%">Action</th>
            </tr>
        </thead>
        <tbody>
            @if (Model != null && Model.Any())
            {
                @foreach (var code in Model)
                {
                    <tr>

                        <td class="text-center">@code.ManagerCode</td>
                        <td class="text-center">@code.StaffCode</td>
                        <td class="text-center">
                            <div class="btn btn-sm">
                                <a asp-action="EditSettings" asp-controller="Setting" asp-route-id="@code.Id" class="btn btn-outline-primary">Edit</a>
                            </div>
                        </td>
                    </tr>
                }
            }
            else
            {
                <tr>
                    <td class="text-center" colspan="12">
                        <div>No restaurant tables available at the moment</div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</form>